name: GitHub Actions Pipeline
on: 
  push:
    branches:
      - master
jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  build:
    name: Build
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - run: echo "Building local container..."
      - run: docker build -t http.server .
      - run: echo "Building finished!"
  stop:
    name: Stop
    runs-on: self-hosted
    steps:
      - run: echo "Stopping existing container"
      - run: docker stop http.server && docker rm http.server || exit 0
      - run: echo "Stopped and deleted!"
  start:
    name: Start
    needs: [checkout, build]
    runs-on: self-hosted
    steps:
      - run: echo "Now starting container..."
      - run: docker run --name "http.server" -d -p 80:80 http.server
      - run: echo "Started!"
  healthcheck:
    name: Healthcheck
    needs: [checkout, build, start]
    runs-on: self-hosted
    steps:
      - run: echo "Healthchecking now..."
      - run: curl --fail http://localhost/testme || exit 1
      - run: echo "Healthy!"